### ISSUE TITLE
bug: desktop app all broken by 5.0.30

### ISSUE THREAD

**Issue by TiteiKo** [Supamiu/ffxiv-teamcraft#772]
## Environment

Windows desktop v5.0.30, happened upon upgrading from v5.0.29 last night.

## Current behavior

Desktop app screenshot:
![image](https://user-images.githubusercontent.com/248372/52999748-e2347100-3426-11e9-901f-4a069d972ec3.png)

Note that it seems all good on the browser version:
![image](https://user-images.githubusercontent.com/248372/52999787-0001d600-3427-11e9-8d89-3e220fb90391.png)

Problems noted:
* header as seen on the screenshot
* clicking on jobs to open the rotations/gathering panels doesn't work, you have to click on the job, then click on a menu item to open the panel
* same for optimized path modal, layout changing modal and so on and so forth

## Steps to reproduce

1. Open a list
2. Click on the layout button
3. Nothing happens
4. Click on a menu item
5. You go to the menu AND the layout panel pops up

**Comment by TiteiKo** [comment]
Ok, so it looks like it's linked to the layout personnalisation:

* on the browser version, header and modals get all screwy when switching to a custom layout
* on the desktop version, header and modals get all righty when switching back to the default layout

**Comment by Supamiu** [comment]
Heya, thanks for the report :)

This bug was introduced by #759 and I didn't see it before, I fixed it in https://github.com/Supamiu/ffxiv-teamcraft/commit/41988ed4f64aacf7ccf480a9f3e98f4e95b541ea and I'm currently releasing 5.0.31 to publish this fix for everyone.

**Comment by TiteiKo** [comment]
Sorry but 5.0.31 didn't fix it :( 

![image](https://user-images.githubusercontent.com/248372/53008339-71e31b00-3439-11e9-878f-f106648b8de1.png)

**Comment by Supamiu** [comment]
Indeed it has been reported to me, I forgot one element inside the fix and my tests didn't detect it. I'm pushing 5.0.32 right now.

**Comment by TiteiKo** [comment]
All good now, thanks a lot for the quickness ❤️
