### ISSUE TITLE
Bug: Grade 3 Wheels (Company Buffs) Cannot be added to lists.

### ISSUE THREAD

**Issue by Brimcon** [Supamiu/ffxiv-teamcraft#96]
As mentioned, for some reason these items cannot be added into lists, I click to add into a list and nothing happens.

I previously even had a list of a Grade 3 Wheel, it said it was outdated, updating the list gives an infinite gif loop that goes nowhere.

Edit: Inspecting the element gives this error:

main.384634ef8e0a182be165.bundle.js:1 TypeError: Cannot read property 'slot' of undefined
    at main.384634ef8e0a182be165.bundle.js:1
    at n.getGatheredBy (main.384634ef8e0a182be165.bundle.js:1)
    at main.384634ef8e0a182be165.bundle.js:1
    at Array.forEach (<anonymous>)
    at e.project (main.384634ef8e0a182be165.bundle.js:1)
    at e._next (vendor.cce8e624054650339cda.bundle.js:1)
    at e.T14+.e.next (vendor.cce8e624054650339cda.bundle.js:1)
    at e._next (vendor.cce8e624054650339cda.bundle.js:1)
    at e.T14+.e.next (vendor.cce8e624054650339cda.bundle.js:1)
    at e._next (vendor.cce8e624054650339cda.bundle.js:1)

**Comment by Supamiu** [comment]
Thank you for your report, this is fixed in 2.4.2, which is being released at the same time I wrote this answer.

**Comment by Brimcon** [comment]
The Bug is back. Cannot add Company Wheels to lists once more.
